# Generated by Django 4.2.5 on 2023-10-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
